# Generated by Django 4.0.6 on 2022-08-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='star',
        ),
    ]
