# Generated by Django 4.0.6 on 2022-08-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_rename_star_id_reviews_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.IntegerField(verbose_name='Значение'),
        ),
    ]
